# Generated by Django 5.2.8 on 2025-12-05 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lifecycle', '0014_rename_last_contract_date_and_more'),
        ('users', '0015_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarelifecycle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='license',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='supportcontract',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='supportcontractassignment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='supportsku',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
    ]
